import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { SUPABASE_URL, SUPABASE_ANON_KEY } from './config.js';
if (SUPABASE_URL.includes('TU-PROYECTO') || SUPABASE_ANON_KEY.includes('PON_AQUI')) {
  document.getElementById('login-error').textContent = 'Antes de usar la app, configura config.js con tu proyecto Supabase.';
}
const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
let session = null;

(()=>{'use strict';const tables={players:'futbol_personal_jugadores',matches:'futbol_personal_partidos'};const state={mode:'7',tab:'plantilla',players:[],matches:[],draft:null,editing:null,playerId:null,busy:false};const el=id=>document.getElementById(id);const safe=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));const id=()=>crypto.randomUUID();const roster=()=>state.players.filter(p=>p.modalidad===state.mode).sort((a,b)=>a.nombre.localeCompare(b.nombre,'es'));const games=()=>state.matches.filter(p=>p.modalidad===state.mode).sort((a,b)=>b.fecha.localeCompare(a.fecha));const entries=match=>{try{let items=JSON.parse(match.participaciones||'[]');return Array.isArray(items)?items:[]}catch{return[]}};const avatar=player=>player?.foto?.startsWith('data:image/')?`<img class="avatar" src="${safe(player.foto)}" alt="">`:`<div class="avatar">${safe((player?.nombre||'?')[0].toUpperCase())}</div>`;
async function request(table,{record,recordId,method}={}){
  if (!session?.user?.id) throw Error('Vuelve a iniciar sesión.');
  const owner_id = session.user.id;
  const source = supabase.from(tables[table]);
  let query;
  if (method === 'POST') query = source.insert({...record, owner_id}).select().single();
  else if (method === 'PUT') query = source.update(record).eq('id', recordId).eq('owner_id', owner_id).select().single();
  else if (method === 'DELETE') query = source.delete().eq('id', recordId).eq('owner_id', owner_id).select().single();
  else query = source.select('*').eq('owner_id', owner_id).order('created_at', {ascending:false}).limit(10000);
  const {data,error} = await query;
  if (error) throw Error(error.message);
  return method ? data : {items:data};
}
function notify(text,ok=false){el('message').innerHTML=text?`<div class="message ${ok?'ok':''}">${safe(text)}</div>`:'';if(text)scrollTo({top:0,behavior:'smooth'})}async function load(){try{let [p,m]=await Promise.all([request('players',{all:true}),request('matches',{all:true})]);state.players=p.items||[];state.matches=m.items||[];render()}catch(error){notify(error.message)}}
function totals(playerId){return games().reduce((result,game)=>{let entry=entries(game).find(item=>item.id===playerId);if(entry){result.games++;result.starts+=Number(!!entry.starter);result.minutes+=Number(entry.minutes)||0;result.goals+=Number(entry.goals)||0}return result},{games:0,starts:0,minutes:0,goals:0})}
function render(){document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('on',b.dataset.mode===state.mode));document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('on',b.dataset.tab===state.tab));let items=games().flatMap(entries);el('stats').innerHTML=[['Jugadores',roster().length],['Partidos',games().length],['Minutos',items.reduce((a,b)=>a+(Number(b.minutes)||0),0)],['Goles',items.reduce((a,b)=>a+(Number(b.goals)||0),0)]].map(([name,count])=>`<div class="stat"><small>${name}</small><b>${count}</b></div>`).join('');el('view').innerHTML=state.draft?editor():state.tab==='plantilla'?playersView():state.tab==='partidos'?matchesView():summary()}
function playersView(){return `<section class="panel"><div class="top"><div><h2>Plantilla · Fútbol ${state.mode}</h2><p class="muted">Añade jugadores con su nombre y foto.</p></div><button class="primary" data-action="add-player">+ Jugador</button></div>${roster().length?`<div class="list">${roster().map(p=>{let t=totals(p.id);return `<div class="row">${avatar(p)}<div class="info"><strong>${safe(p.nombre)}</strong><small>${t.games} partidos · ${t.minutes} min · ${t.goals} goles · ${t.starts} titularidades</small></div><div class="actions"><button class="secondary small" data-action="edit-player" data-id="${safe(p.id)}">Editar</button><button class="danger small" data-action="delete-player" data-id="${safe(p.id)}">Borrar</button></div></div>`}).join('')}</div>`:'<div class="blank"><b>Sin jugadores todavía</b>Añade tu primer jugador para empezar.</div>'}</section>`}
function matchesView(){return `<section class="panel"><div class="top"><div><h2>Partidos · Fútbol ${state.mode}</h2><p class="muted">${state.mode==='7'?'Hasta 14 convocados y 7 titulares':'Selecciona el 11 inicial'} por partido.</p></div><button class="primary" data-action="add-match">+ Partido</button></div>${games().length?`<div class="list">${games().map(m=>{let list=entries(m);return `<div class="row"><div class="avatar">⚽</div><div class="info"><strong>${safe(m.rival)}</strong><small>${safe(m.fecha)} · ${list.length} convocados · ${list.reduce((a,b)=>a+(Number(b.minutes)||0),0)} min · ${list.reduce((a,b)=>a+(Number(b.goals)||0),0)} goles</small><small>Inicial: ${list.filter(i=>i.starter).map(i=>safe(state.players.find(p=>p.id===i.id)?.nombre||i.nombre)).join(', ')}</small></div><div class="actions"><button class="secondary small" data-action="edit-match" data-id="${safe(m.id)}">Editar</button><button class="danger small" data-action="delete-match" data-id="${safe(m.id)}">Borrar</button></div></div>`}).join('')}</div>`:'<div class="blank"><b>No hay partidos aún</b>Crea uno para apuntar alineación, minutos y goles.</div>'}</section>`}
function summary(){let players=roster().map(p=>({p,t:totals(p.id)})).sort((a,b)=>b.t.minutes-a.t.minutes);return `<section class="panel"><div class="top"><div><h2>Datos por jugador</h2><p class="muted">Acumulados de todos los partidos de Fútbol ${state.mode}.</p></div></div>${players.length?`<div class="list">${players.map(({p,t})=>`<div class="row">${avatar(p)}<div class="info"><strong>${safe(p.nombre)}</strong><small>${t.games} partidos · ${t.starts} veces en el inicial</small></div><span class="badge">${t.minutes} min</span><span class="badge">${t.goals} goles</span></div>`).join('')}</div>`:'<div class="blank"><b>Sin datos</b>Añade jugadores y partidos.</div>'}</section>`}
function openEditor(match){let date=new Date();state.tab='partidos';state.editing=match?.id||null;state.draft={fecha:match?.fecha||`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`,rival:match?.rival||'',players:match?entries(match).map(item=>({...item})):[]};render()}
function editor(){let d=state.draft;let starters=d.players.filter(p=>p.starter);let choices=roster().concat(d.players.filter(item=>!state.players.some(p=>p.id===item.id)).map(item=>({id:item.id,nombre:item.nombre})));return `<section class="panel"><div class="top"><div><h2>${state.editing?'Editar':'Nuevo'} partido · Fútbol ${state.mode}</h2><p class="muted">${d.players.length}${state.mode==='7'?' / 14':''} convocados · ${starters.length} / ${state.mode} titulares</p></div><button class="secondary small" data-action="cancel">Volver</button></div><div class="formgrid"><label class="field">Fecha<input id="date" type="date" value="${safe(d.fecha)}"></label><label class="field">Rival o nombre del partido<input id="rival" maxlength="100" placeholder="Ej. Contra Los Pinos" value="${safe(d.rival)}"></label></div><h2>Convocatoria</h2><div class="playerline muted"><span>Jugador</span><span>Conv.</span><span>Inicial</span><span>Minutos</span><span>Goles</span></div>${choices.length?choices.map(p=>{let item=d.players.find(i=>i.id===p.id);return `<div class="playerline"><div class="who">${avatar(p)}<span>${safe(p.nombre)}</span></div><label><input type="checkbox" data-field="called" data-id="${safe(p.id)}" aria-label="Convocar a ${safe(p.nombre)}" ${item?'checked':''}></label><label><input type="checkbox" data-field="starter" data-id="${safe(p.id)}" aria-label="Titular: ${safe(p.nombre)}" ${item?.starter?'checked':''}></label><input type="number" data-field="minutes" data-id="${safe(p.id)}" min="0" max="999" step="1" value="${item?.minutes??0}" aria-label="Minutos de ${safe(p.nombre)}" ${item?'':'disabled'}><input type="number" data-field="goals" data-id="${safe(p.id)}" min="0" max="99" step="1" value="${item?.goals??0}" aria-label="Goles de ${safe(p.nombre)}" ${item?'':'disabled'}></div>`}).join(''):'<div class="blank"><b>Faltan jugadores</b>Añádelos primero en Plantilla.</div>'}<h3>${state.mode} inicial</h3><div class="lineup">${starters.length?starters.map(i=>`<span class="badge">${safe(state.players.find(p=>p.id===i.id)?.nombre||i.nombre)}</span>`).join(''):'<span class="muted">Elige los titulares para ver la alineación.</span>'}</div><button class="primary" data-action="save" ${state.busy?'disabled':''}>Guardar partido</button> <button class="secondary" data-action="cancel">Cancelar</button></section>`}
function showPlayer(player){state.playerId=player?.id||null;el('playerform').reset();el('playerform').elements.nombre.value=player?.nombre||'';el('preview').src=player?.foto||'';el('preview').classList.toggle('hidden',!player?.foto);el('dialogtitle').textContent=player?'Editar jugador':'Nuevo jugador';el('dialog').classList.remove('hidden');el('playerform').elements.nombre.focus()}
async function compress(file){if(!file.type.startsWith('image/'))throw Error('Selecciona una imagen válida.');if(file.size>10*1024*1024)throw Error('La imagen supera 10 MB.');let bitmap=await createImageBitmap(file);let canvas=document.createElement('canvas');let ratio=Math.min(1,240/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*ratio));canvas.height=Math.max(1,Math.round(bitmap.height*ratio));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/jpeg',.7)}
el('playerform').addEventListener('submit',async event=>{event.preventDefault();let button=event.target.querySelector('[type=submit]');button.disabled=true;try{let original=state.players.find(p=>p.id===state.playerId);let file=event.target.elements.foto.files[0];let name=event.target.elements.nombre.value.trim();if(!name)throw Error('Escribe un nombre.');let record={id:original?.id||id(),modalidad:state.mode,nombre:name,foto:file?await compress(file):original?.foto||''};await request('players',{record,recordId:original?.id,method:original?'PUT':'POST'});el('dialog').classList.add('hidden');notify('Jugador guardado.',true);await load()}catch(error){notify(error.message)}finally{button.disabled=false}});el('close').onclick=()=>el('dialog').classList.add('hidden');el('dialog').onclick=event=>{if(event.target.id==='dialog')el('dialog').classList.add('hidden')};
el('playerform').elements.foto.onchange=async event=>{if(!event.target.files[0])return;try{el('preview').src=await compress(event.target.files[0]);el('preview').classList.remove('hidden')}catch(error){notify(error.message)}};
async function remove(table,recordId){let p=state.players.find(i=>i.id===recordId),m=state.matches.find(i=>i.id===recordId);if(!confirm(`¿Borrar ${p?.nombre||m?.rival||'este registro'}? ${p?'Sus partidos conservarán su nombre, pero no aparecerá en estadísticas de la plantilla.':'Se descontarán sus minutos y goles.'}`))return;try{await request(table,{recordId,method:'DELETE'});notify('Registro borrado.',true);await load()}catch(error){notify(error.message)}}
function changeEntry(field,recordId,input){let d=state.draft;let entry=d.players.find(p=>p.id===recordId);if(field==='called'||field==='starter'){if(input.checked&&!entry){if(state.mode==='7'&&d.players.length>=14){input.checked=false;notify('Máximo 14 convocados para fútbol 7.');return}let player=state.players.find(p=>p.id===recordId);entry={id:recordId,nombre:player?.nombre||'Jugador',minutes:0,goals:0,starter:false};d.players.push(entry)}if(field==='called'&&!input.checked)d.players=d.players.filter(p=>p.id!==recordId);if(field==='starter'&&entry){if(input.checked&&d.players.filter(p=>p.starter).length>=Number(state.mode)){input.checked=false;notify(`Solo ${state.mode} titulares como máximo.`);return}entry.starter=input.checked}render()}else if(entry)entry[field]=input.value}
async function save(){if(state.busy)return;let d=state.draft;d.fecha=el('date').value;d.rival=el('rival').value.trim();if(!d.fecha||!d.rival){notify('Indica fecha y rival.');return}if(d.players.length<Number(state.mode)){notify(`Necesitas al menos ${state.mode} convocados.`);return}if(d.players.filter(p=>p.starter).length!==Number(state.mode)){notify(`Selecciona exactamente ${state.mode} titulares.`);return}let items=d.players.map(p=>({...p,minutes:Number(p.minutes),goals:Number(p.goals),nombre:state.players.find(i=>i.id===p.id)?.nombre||p.nombre}));if(items.some(p=>!Number.isInteger(p.minutes)||p.minutes<0||p.minutes>999||!Number.isInteger(p.goals)||p.goals<0||p.goals>99)){notify('Minutos y goles deben ser enteros válidos.');return}state.busy=true;render();try{let record={id:state.editing||id(),modalidad:state.mode,fecha:d.fecha,rival:d.rival,participaciones:JSON.stringify(items)};await request('matches',{record,recordId:state.editing,method:state.editing?'PUT':'POST'});state.draft=null;state.editing=null;notify('Partido y alineación guardados.',true);await load()}catch(error){notify(error.message)}finally{state.busy=false;render()}}
document.addEventListener('click',event=>{let mode=event.target.closest('[data-mode]'),tab=event.target.closest('[data-tab]'),button=event.target.closest('[data-action]');if(mode){state.mode=mode.dataset.mode;state.draft=null;state.editing=null;notify('');render();return}if(tab){state.tab=tab.dataset.tab;state.draft=null;state.editing=null;notify('');render();return}if(!button)return;let recordId=button.dataset.id;switch(button.dataset.action){case'add-player':showPlayer();break;case'edit-player':showPlayer(state.players.find(p=>p.id===recordId));break;case'delete-player':remove('players',recordId);break;case'add-match':openEditor();break;case'edit-match':openEditor(state.matches.find(m=>m.id===recordId));break;case'delete-match':remove('matches',recordId);break;case'cancel':state.draft=null;state.editing=null;render();break;case'save':save();break}});
el('view').addEventListener('change',event=>{let field=event.target.dataset.field;if(field)changeEntry(field,event.target.dataset.id,event.target);if(event.target.id==='date'&&state.draft)state.draft.fecha=event.target.value});el('view').addEventListener('input',event=>{let field=event.target.dataset.field;if(field&&(field==='minutes'||field==='goals'))changeEntry(field,event.target.dataset.id,event.target);if(event.target.id==='rival'&&state.draft)state.draft.rival=event.target.value});render();
const login=document.getElementById('login');
const appRoot=document.getElementById('app');
function showSession(nextSession){
  session=nextSession;
  login.hidden=!!session;
  appRoot.hidden=!session;
  if(session) load();
  else {state.players=[];state.matches=[];state.draft=null;render();}
}
document.getElementById('loginform').addEventListener('submit',async event=>{
  event.preventDefault();
  const button=event.target.querySelector('button[type=submit]');
  button.disabled=true;
  try {
    const {error}=await supabase.auth.signInWithPassword({email:event.target.elements.email.value.trim(),password:event.target.elements.password.value});
    if(error) throw error;
    event.target.reset();
    document.getElementById('login-error').textContent='';
  } catch(error) {document.getElementById('login-error').textContent=error.message;}
  finally {button.disabled=false;}
});
document.getElementById('logout').addEventListener('click',async()=>{
  const {error}=await supabase.auth.signOut();
  if(error) notify(error.message);
});
supabase.auth.onAuthStateChange((_event,nextSession)=>{queueMicrotask(()=>showSession(nextSession));});
supabase.auth.getSession().then(({data,error})=>{
  if(error) document.getElementById('login-error').textContent=error.message;
  else showSession(data.session);
});

})();
